---
title: "MATH2320 Assignment 1"
author: "Benjamin G. Moran, c3076448@uon.edu.au"
date: "29 July 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Due:** 5pm Tuesday 2nd August 2016.

This is the first of the weekly assignments that you will receive this semester in MATH2320: Linear Algebra. In a typical week your assignment will consist of an introductory level question from the current week's lectures, which is preparation for your workshop, and some harder review questions from the previous week. For this first assignment, all questions are introductory level questions relating to the Monday lecture of the first week.

If you have any questions about this assignment, please see or email your lecturer for this course, Dr Daniel Sutherland <Daniel.Sutherland@newcastle.edu.au>.

***


**Recall:** a _Vector Space_ $V = (S, +, \cdot)$ comprises a set _S_ of objects we call vectors, a field $\mathbb F$ (such as the real numbers $\mathbb R$ or complex numbers $\mathbb C$), an operation '$+$' such that the sum of any two vectors u and v in S is another vector u + v in S, and another operation '$\cdot$' such that the product of any element of the field, k, with any element of the set of vectors, v, is a vector k v (often written kv).

***

1. Consider the set of polynomials of degree less than or equal to one, with real coefficients: $$P_1(x) := \{a + bx : a, b \in \mathbb{R}\}$$ This set is a vector space over $\mathbb{R}$, under standard addition of polynomials and standard multiplication of real numbers by polynomials. 
*Prove that the vectors in $P_1(x)$ obey the commutative law of vector addition.*

    **Answer:** Suppose we have two polynomials, $p(x)= \theta_1 + \gamma_1x$ and $q(x)=\theta_2 + \gamma_2x$, such that $$p(x), q(x) \in P_1(x): \theta_1, \theta_2, \gamma_1, \gamma_2 \in \mathbb{R},$$ then we get that: $$\begin{aligned} (p + q)(x) &= (\theta_1 + \gamma_1x) + (\theta_2 + \gamma_2x) \\ &= (\theta_1 + \theta_2) + (\gamma_1 + \gamma_2)(x) \\ &= (\theta_2 + \theta_1) + (\gamma_2 + \gamma_1)(x) \\ &= (\theta_2 + \gamma_2x) + (\theta_1 + \gamma_1x) \\ &= (q + p)(x) \end{aligned}$$ Therefore, the polynomials in $P_1(x)$ obey the commutative law of vector addition.

***

2.	Consider the set _S_ of polynomials of degree less than or equal to one, with real coefficients, whose constant term is equal to `1': $$S := \{1 + bx : a, b \in \mathbb{R}\}$$ 

    *Prove that under the usual addition of polynomials, S fails to be a vector space over R.* 
    
    *Hint: for any set to be made into a vector space, addition and scalar multiplication must be well-defined. Well-defined addition means that for any two vectors in the set, their sum must also be in the set. Well-defined scalar multiplication means that for any scalar in the field and vector in the set, their product must also be a vector in the set.*
    
    **Answer:** Suppose we have two polynomials, $p(x)= 1 + \gamma_1x$ and $q(x)=1 + \gamma_2x$, such that $$p(x), q(x) \in S: \gamma_1, \gamma_2 \in \mathbb{R},$$ then, by the usual laws of vector addition we get that: $$\begin{aligned} (p + q)(x) &= (1 + \gamma_1x) + (1 + \gamma_2x) \\ &= (1 + 1) + (\gamma_1 + \gamma_2)(x) \\ &= 2 + (\gamma_1 + \gamma_2)(x)  \notin S \end{aligned}$$ Therefore, the set *S* is not closed under vector addition, which implies that it fails to be a vector space over $\mathbb{R}$. 

***

3. Consider the subset _T_ of $\mathbb{R}^2$ defined as follows: $$T := \{(x, y) : x, y \in \mathbb{R} \text{ such that } y = 3x\}$$

    *Prove that T is a subspace of the vector space $\mathbb{R}^2$.*

    *Hint: if V is a vector space and U is a subset of V , then U is a subspace of V provided that:*

    * _U contains the additive identity $(0 \in U)$,_
    * _U is closed under addition $(u, v \in U$ implies $u + v \in U)$,_
    * _and U is closed under scalar multiplication $(a \in \mathbb{F}$ and $u \in U$ implies $au \in U)$._
    
    **Answer:** Let $x = 0$. Then we get: $$y = 3x = 3(0) = 0 \implies (0,0) \in T.$$ Therefore, the set *T* contains the additive identity.

***

###Submitting your assignment (due 5pm Tuesday 2nd August 2016)

*Submit your assignment in hardcopy in your Demonstrator's pigeonhole in the Assignment boxes near the Maths Clinic, on the opposite wall to the Maths Clinic, left of the door to V109. We also ask that you scan your written work and submit it on the MATH2320 UoNline/Blackboard site as a backup and proof of submission, not as a substitute. __Note that we still require the hardcopy submitted in the Assignment Box for your Demonstrator to mark, even if you have submitted a backup on Blackboard.__*
 
